---
- name: Set UFW default incoming policy to deny
  ufw:
    direction: incoming
    default: deny

- name: Set UFW default outgoing policy to allow
  ufw:
    direction: outgoing
    default: allow

- name: Allow SSH on port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow HTTP on port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow HTTPS on port 443
  ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Enable UFW firewall
  ufw:
    state: enabled
